apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  {{- if or (.Values.plugin.features.acm.enabled) (.Values.plugin.features.incidents.enabled) }}
  name: {{ .Values.plugin.features.name }}
  {{- else }}
  name: {{ template "openshift-console-plugin.name" . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-console-plugin.labels" . | nindent 4 }}
spec:
  backend:
    service:
      basePath: /
      {{- if or (.Values.plugin.features.acm.enabled) (.Values.plugin.features.incidents.enabled) }}
      name: {{ .Values.plugin.features.name }}
      {{- else }}
      name: {{ template "openshift-console-plugin.name" . }}
      {{- end }}
      namespace: {{ .Release.Namespace }}
      port: 9443
    type: Service
  {{- if or (.Values.plugin.features.acm.enabled) (.Values.plugin.features.incidents.enabled) }}
  displayName: {{ .Values.plugin.features.name }}
  {{- else }}
  displayName: {{ template "openshift-console-plugin.name" . }}
  {{- end }}
  i18n:
    loadType: Preload
  proxy:
  - alias: backend
    authorization: UserToken
    endpoint:
      service:
        {{- if or (.Values.plugin.features.acm.enabled) (.Values.plugin.features.incidents.enabled) }}
        name: {{ .Values.plugin.features.name }}
        {{- else }}
        name: {{ template "openshift-console-plugin.name" . }}
        {{- end }}
        namespace: {{ .Release.Namespace }}
        port: 9443
      type: Service
  {{- if and (.Values.plugin.features.acm.enabled) }}
  - alias: alertmanager-proxy
    authorization: UserToken
    endpoint:
      service:
        name: {{ .Values.plugin.features.name }}
        namespace: {{ .Release.Namespace }}
        port: 9444
      type: Service
  - alias: thanos-proxy
    authorization: UserToken
    endpoint:
      service:
        name: {{ .Values.plugin.features.name }}
        namespace: {{ .Release.Namespace }}
        port: 9445
      type: Service
  {{- end }}
